version: '3'

services:
  app:
    image: dd3ll/node-cup
    command: npm start
    depends_on:
      - postgres 
    ports: 
      - '8087:8087'
    volumes:
      - .:/app
  
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=worldcup
    ports:
      - '5432:5432'
    volumes:
      - ./worldcup.sql:/docker-entrypoint-initdb.d/worldcup.sql

  

